#!/bin/zsh
# Cuts a release:  scripts/release.sh <version> [--publish]
#
#   1. sets the version in packaging/Info.plist
#   2. builds dist/AssumeKeycloaker-<version>.zip (team config bundled)
#   3. writes dist/assume-keycloaker.rb: the cask with version + sha256 filled in
#   --publish  also creates the GitHub release on $REPO with the zip, and commits the cask to
#              Casks/ in the tap repo $TAP_REPO. Installed apps pick it up on their next update check.
#
# REPO (default gtalmor/assume-keycloaker) and TAP_REPO (default gtalmor/homebrew-tap) can be overridden.
set -euo pipefail
cd "${0:A:h}/.."

VERSION="${1:?usage: scripts/release.sh <version> [--publish]}"
REPO="${REPO:-gtalmor/assume-keycloaker}"
TAP_REPO="${TAP_REPO:-gtalmor/homebrew-tap}"
[[ "$VERSION" =~ '^[0-9]+\.[0-9]+(\.[0-9]+)?$' ]] || { echo "version must look like 1.2.3"; exit 1; }

/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" -c "Set :CFBundleVersion $VERSION" packaging/Info.plist
./scripts/package.sh
# Nothing team-specific may ship: check the repo and the freshly built app.
./scripts/leak-check.sh

ZIP="dist/AssumeKeycloaker-$VERSION.zip"
SHA=$(shasum -a 256 "$ZIP" | awk '{print $1}')
{ echo "# Generated by assume-keycloaker scripts/release.sh. Edit packaging/homebrew/assume-keycloaker.rb instead."
  sed -e '/^# Template/d' -e '/^# Fill in/d' \
    -e "s|^  version \".*\"|  version \"$VERSION\"|" \
    -e "s|^  sha256 \".*\"|  sha256 \"$SHA\"|" \
    -e "s|github.com/gtalmor/assume-keycloaker|github.com/$REPO|g" \
    packaging/homebrew/assume-keycloaker.rb; } > dist/assume-keycloaker.rb
echo "Cask: dist/assume-keycloaker.rb ($VERSION, $SHA)"

[[ "${2:-}" == "--publish" ]] || { echo "Dry run. Add --publish to release on $REPO and $TAP_REPO."; exit 0; }

command -v gh >/dev/null || { echo "gh (GitHub CLI) is required to publish"; exit 1; }
gh release create "v$VERSION" "$ZIP" --repo "$REPO" --title "Assume Keycloaker $VERSION" \
  --notes "Install: \`brew install --cask ${TAP_REPO/homebrew-/}/assume-keycloaker\` · Update: \`brew upgrade --cask assume-keycloaker\` (or let the app do it)."

TMP=$(mktemp -d)
gh repo clone "$TAP_REPO" "$TMP/tap" -- --depth 1 --quiet
mkdir -p "$TMP/tap/Casks"
cp dist/assume-keycloaker.rb "$TMP/tap/Casks/assume-keycloaker.rb"
git -C "$TMP/tap" add Casks/assume-keycloaker.rb
git -C "$TMP/tap" commit --quiet -m "assume-keycloaker $VERSION"
git -C "$TMP/tap" -c credential.helper= -c 'credential.helper=!gh auth git-credential' push --quiet
echo "Published $VERSION: release on $REPO, cask on $TAP_REPO"
